<?xml version="1.0" encoding="UTF-8" ?>
<!-- 
    Nome: Laura
    Cognome: Mazzagufo
    Data: 02/04/2021
    Nome file: "esercizio-validazione-internalDTD.xml"
    Descrizione: esercizio del corso di Codifica di testi
    Consegna: 
            -	Includere all’interno di un documento XML la dichiarazione del tipo, definire internamente gli elementi e gli attributi e validare;
            -	Inserire nel prologo di un documento XML la dichiarazione del tipo di documento e validare. Creare un file esterno con estensione .dtd prima di includerlo nel prologo XML.

-->

<!-- INTERNAL DTD:-->
<!DOCTYPE TEI [
<!ELEMENT TEI (padre,elemento+,altroElemento?,altroPadre)>

<!ELEMENT padre (figlio)> 
<!ELEMENT elemento (#PCDATA)>
<!ELEMENT altroElemento (#PCDATA)>
<!ELEMENT altroPadre (#PCDATA|altroFiglio)*>

<!ELEMENT figlio (#PCDATA)>
<!ELEMENT altroFiglio (#PCDATA)>

<!ATTLIST padre color ID #REQUIRED> <!-- ID deve essere univoco -->
<!ATTLIST figlio attribute IDREF #IMPLIED> <!-- IDREF deve riferirsi a ID -->
<!ATTLIST elemento type CDATA #IMPLIED>
<!ATTLIST altroElemento lang NMTOKEN #IMPLIED>
<!ATTLIST altroPadre id ID #REQUIRED> <!-- ID deve essere univoco -->
<!ATTLIST altroFiglio ref IDREF #REQUIRED> <!-- IDREF deve riferirsi a ID -->
<!ATTLIST altroFiglio attribute CDATA #FIXED "nome">
]>

<TEI>
    <padre color="blue">
        <figlio attribute="blue">Questo è un elemento testuale</figlio>
    </padre>

    <elemento type="testo">Questo è un elemento testuale</elemento> <!-- <elemento>: una o più occorrenze-->

    <elemento>Questo è un altro elemento testuale</elemento> <!-- <altroElemento>: zero o una occorrenza -->

    <altroPadre id="LM">
        Questo è un elemento misto.
        <altroFiglio attribute="nome" ref="LM">Questo è un elemento testuale.</altroFiglio>
    </altroPadre>

</TEI>